name: img2sound
channels:
  - defaults
dependencies:
  - ca-certificates=2017.08.26
  - certifi=2017.11.5
  - libedit=3.1
  - libffi=3.2.1
  - ncurses=6.0
  - openssl=1.0.2n
  - pip=9.0.1
  - python=3.6.4
  - readline=7.0
  - setuptools=36.5.0
  - sqlite=3.20.1
  - tk=8.6.7
  - wheel=0.30.0
  - xz=5.2.3
  - zlib=1.2.11
  - pip:
    - aniso8601==2.0.0
    - appnope==0.1.0
    - audioread==2.1.5
    - awscli==1.11.178
    - bleach==2.1.2
    - botocore==1.7.36
    - click==6.7
    - colorama==0.3.7
    - cycler==0.10.0
    - cython==0.27.3
    - decorator==4.2.1
    - docutils==0.14
    - entrypoints==0.2.3
    - flask==0.12.2
    - flask-cors==3.0.3
    - flask-restful==0.3.6
    - flask-script==2.0.6
    - html5lib==1.0.1
    - ipykernel==4.8.0
    - ipython==6.2.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.1.1
    - itsdangerous==0.24
    - jedi==0.11.1
    - jinja2==2.10
    - jmespath==0.9.3
    - joblib==0.11
    - jsonschema==2.6.0
    - jupyter==1.0.0
    - jupyter-client==5.2.2
    - jupyter-console==5.2.0
    - jupyter-core==4.4.0
    - jupyterlab==0.31.8
    - jupyterlab-launcher==0.10.5
    - librosa==0.6.0
    - llvmlite==0.22.0
    - markupsafe==1.0
    - matplotlib==2.1.2
    - mistune==0.8.3
    - nbconvert==5.3.1
    - nbformat==4.4.0
    - notebook==5.4.0
    - numba==0.37.0
    - numpy==1.14.0
    - pandas==0.22.0
    - pandocfilters==1.4.2
    - parso==0.1.1
    - pexpect==4.3.1
    - pickleshare==0.7.4
    - prompt-toolkit==1.0.15
    - ptyprocess==0.5.2
    - pyasn1==0.3.7
    - pygments==2.2.0
    - pyparsing==2.2.0
    - python-dateutil==2.6.1
    - pytz==2017.3
    - pyyaml==3.12
    - pyzmq==16.0.4
    - qtconsole==4.3.1
    - resampy==0.2.0
    - rsa==3.4.2
    - s3transfer==0.1.11
    - scikit-learn==0.19.1
    - scipy==1.0.0
    - seaborn==0.8.1
    - send2trash==1.4.2
    - simplegeneric==0.8.1
    - six==1.11.0
    - terminado==0.8.1
    - testpath==0.3.1
    - tornado==4.5.3
    - traitlets==4.3.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - werkzeug==0.14.1
    - widgetsnbextension==3.1.3
